tests = {
    "logic": [
        {"question": "Bir ota-onaning 6 o‘g‘li bor, har birining bir opasi bor. Jami nechta farzand bor?",
         "options": ["6", "7", "12", "8"], "answer": 1},
        {"question": "Qaysi oyda 28 kun bor?",
         "options": ["Faqat fevral", "Yanvar", "Har oy", "Aprel"], "answer": 2},
        {"question": "Agar uchta mushuk uchta sichqonni uch daqiqada tutsalar, bitta mushuk bitta sichqonni nechada tutadi?",
         "options": ["1 daqiqa", "3 daqiqa", "9 daqiqa", "6 daqiqa"], "answer": 1},
        {"question": "5 ta mashina 5 ta g‘isht tashishni 5 daqiqa qilsa, 100 ta mashina 100 ta g‘ishtni nech daqiqada tashiydi?",
         "options": ["5", "100", "20", "50"], "answer": 0},
        {"question": "2 ta ota, 2 ta o‘g‘il ovga chiqdi, lekin jami 3 ta odam bor edi. Bu qanday mumkin?",
         "options": ["Yolg‘on", "Ota, o‘g‘il va nabira", "Ikkita aka va bitta uka", "Ustoz va ikki shogird"], "answer": 1},
        {"question": "Uchta sham yonib turardi, bittasi o‘chirildi. Nechta sham qoldi?",
         "options": ["2 ta", "3 ta", "1 ta", "Hech biri"], "answer": 1},
        {"question": "Bir kishi kechasi chiroq yoqmasdan qora mashinani ko‘rib qolgan. Qanday qilib?",
         "options": ["Mashina oq edi", "Oy nurida ko‘rdi", "Ko‘rmadi", "Mashinada chiroq yonib turgan"], "answer": 1},
        {"question": "10 dan 100 gacha nechta “9” raqami bor?",
         "options": ["10", "11", "20", "19"], "answer": 1},
        {"question": "Bir qishloqda 5 ta usta yashardi. Har biri bitta uy qurdi. Nechta uy qurildi?",
         "options": ["1 ta", "5 ta", "25 ta", "Cheksiz"], "answer": 1},
        {"question": "2+2=4, 3+3=6, unda 4+4 nechchiga teng?",
         "options": ["6", "8", "10", "12"], "answer": 1},
        {"question": "Uchta qush daraxtda o‘tirardi. Ovchi bittasini otib oldi. Daraxtda nechta qoldi?",
         "options": ["3 ta", "2 ta", "Hech biri", "1 ta"], "answer": 2},
        {"question": "6 ta olmani 6 bola 1 tadan oldi. Qanday qilib bitta olma savatda qoldi?",
         "options": ["Savatga hech kim tegmadi", "Oxirgi bola savatni oldi", "Bir bola olmadi", "Savat buzilgan"], "answer": 1},
        {"question": "Kunlar ichida faqat 3 harfdan iborat bo‘lgani qaysi?",
         "options": ["Yak", "Shan", "Yakshanba", "Payshanba"], "answer": 0},
        {"question": "Bugun seshanba bo‘lsa, ertangi kundan keyin qaysi kun bo‘ladi?",
         "options": ["Payshanba", "Chorshanba", "Juma", "Shanba"], "answer": 1},
        {"question": "1000 dan 40 ni olib tashlab, 5 marta takrorlansa qancha qoladi?",
         "options": ["800", "900", "600", "760"], "answer": 0},
    ],

    # 🔹 Keyinchalik bu yerga boshqa fanlar va sinflarni qo‘shishingiz mumkin
}
